# Generated by Django 5.2 on 2025-04-19 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vmdash', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaintenanceTypes',
            new_name='MaintenanceType',
        ),
    ]
