# Generated by Django 5.2 on 2025-04-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmdash', '0004_alter_car_maintenance_alter_car_miles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='maintenance',
            field=models.ManyToManyField(blank=True, to='vmdash.maintenancetype'),
        ),
        migrations.AlterField(
            model_name='car',
            name='miles',
            field=models.IntegerField(default=0, help_text='The miles that are on the car', verbose_name='Miles'),
        ),
    ]
