# Generated by Django 5.2 on 2025-04-22 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('vmdash', '0005_alter_car_maintenance_alter_car_miles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleMaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the maintenance type.', max_length=64, unique=True, verbose_name='Name')),
                ('description', models.TextField(help_text='The description of the maintenance type.', verbose_name='Description')),
                ('time_interval', models.IntegerField(default=0, help_text='The time interval of the maintenance type.', verbose_name='Time Interval')),
                ('miles_interval', models.IntegerField(default=0, help_text='The miles interval of the maintenance type.', verbose_name='Miles Interval')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the make.', max_length=64, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='maintenancetype',
            name='records',
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed Vehicle', max_length=64, verbose_name='Name')),
                ('vin', models.CharField(blank=True, default='', help_text='The VIN of the vehicle.', max_length=17, unique=True, verbose_name='VIN')),
                ('plate', models.CharField(blank=True, default='', help_text='The plate of the vehicle.', max_length=16, unique=True, verbose_name='Plate')),
                ('year', models.IntegerField(default=0, help_text='The year of the vehicle.', verbose_name='Year')),
                ('mileage', models.IntegerField(default=0, help_text='The mileage of the vehicle.', verbose_name='Mileage')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_by', to=settings.AUTH_USER_MODEL)),
                ('shared_to_edit', models.ManyToManyField(blank=True, help_text='Users this vehicle is shared to, these people have permission to edit the vehicle.', related_name='shared_to_edit_to', to=settings.AUTH_USER_MODEL)),
                ('shared_to_view', models.ManyToManyField(blank=True, help_text='Users this vehicle is shared to, these people have permission to view the vehicle.', related_name='shared_to_view_to', to=settings.AUTH_USER_MODEL)),
                ('make', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='make_of', to='vmdash.vehiclemake')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleMaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('miles', models.IntegerField(default=0, verbose_name='Miles')),
                ('description', models.TextField(default='', verbose_name='Description')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_record_of', to='vmdash.vehicle')),
                ('type', models.ForeignKey(default=None, help_text='The type of maintenance.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record_of', to='vmdash.vehiclemaintenancetype')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the manufacturer.', max_length=64, unique=True, verbose_name='Name')),
                ('country', models.ForeignKey(help_text='Country that this manufacturer is located in', on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_of', to='location.country')),
            ],
        ),
        migrations.AddField(
            model_name='vehiclemake',
            name='manufacturer',
            field=models.ForeignKey(help_text='Manufacturer that this make belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='make_of', to='vmdash.vehiclemanufacturer'),
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the model.', max_length=64, unique=True, verbose_name='Name')),
                ('make', models.ForeignKey(help_text='Make that this model belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='model_of', to='vmdash.vehiclemake')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_of', to='vmdash.vehiclemodel'),
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='MaintenanceRecord',
        ),
        migrations.DeleteModel(
            name='MaintenanceType',
        ),
    ]
