# Generated by Django 5.2 on 2025-04-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmdash', '0007_alter_vehicle_make_alter_vehicle_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(blank=True, default='', help_text='The plate of the vehicle.', max_length=16, verbose_name='Plate'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(blank=True, default='', help_text='The VIN of the vehicle.', max_length=17, verbose_name='VIN'),
        ),
    ]
