# Generated by Django 4.2.20 on 2025-04-23 02:57

import apps.filestore.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=500)),
                ('file', models.FileField(null=True, upload_to=apps.filestore.models.filename_format)),
                ('filetype', models.CharField(max_length=25)),
                ('views', models.PositiveBigIntegerField(default=0)),
                ('downloads', models.PositiveBigIntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_altered', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
