# Generated by Django 5.2 on 2025-04-19 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filestore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='downloads',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
