# Generated by Django 5.1.7 on 2025-04-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filestore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default='_', max_length=50),
            preserve_default=False,
        ),
    ]
