# Generated by Django 5.1.7 on 2025-04-07 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filestore', '0002_video_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='slug',
        ),
    ]
