# Generated by Django 5.2 on 2025-04-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filestore', '0003_remove_video_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=500)),
                ('file', models.FileField(null=True, upload_to='')),
                ('filetype', models.CharField(max_length=25)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_altered', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.AlterField(
            model_name='video',
            name='videofile',
            field=models.FileField(null=True, upload_to='mp4/'),
        ),
    ]
