# Generated by Django 5.2 on 2025-04-07 23:52

import apps.filestore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filestore', '0004_file_alter_video_videofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(null=True, upload_to=apps.filestore.models.filename_format),
        ),
    ]
