# Generated by Django 5.2 on 2025-04-07 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filestore', '0005_alter_file_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
