# Generated by Django 5.2 on 2025-04-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filestore', '0006_delete_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='views',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
