# Generated by Django 5.2 on 2025-04-23 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikiarticle',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, help_text='Tags associated with the article.', related_name='articles', to='wiki.wikitag', verbose_name='Tags'),
        ),
    ]
