# Generated by Django 5.2 on 2025-04-23 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_alter_wikiarticle_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikiarticle',
            name='grub',
            field=models.CharField(default='django', help_text='Grub is a unique identifier for the article, used in the URL.', max_length=255, unique=True, verbose_name='Grub'),
            preserve_default=False,
        ),
    ]
