# Generated by Django 4.2.20 on 2025-04-23 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('escalated', 'Escalated'), ('critical', 'Critical'), ('closed', 'Closed')], max_length=32)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_altered', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_by', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_reason', models.TextField(help_text='Explanation of why the user is being reported.', max_length=1024, verbose_name='Reason for Report')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', help_text='The current status of the report.', max_length=32, verbose_name='Status')),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes on how the report was resolved.', max_length=1024, null=True, verbose_name='Resolution Notes')),
                ('resolution_date', models.DateTimeField(default=None, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_altered', models.DateTimeField(auto_now=True)),
                ('reported_user', models.ForeignKey(help_text='The user who was reported.', on_delete=django.db.models.deletion.CASCADE, related_name='reported_by', to=settings.AUTH_USER_MODEL, verbose_name='Reported User')),
                ('reporting_user', models.ForeignKey(help_text='The user who filed the report.', on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL, verbose_name='Reporting User')),
                ('resolution_user', models.ForeignKey(help_text='The staff member that resolved this report.', on_delete=django.db.models.deletion.CASCADE, related_name='resolved_by', to=settings.AUTH_USER_MODEL, verbose_name='Resolution User')),
            ],
            options={
                'verbose_name': 'User Report',
                'verbose_name_plural': 'User Reports',
            },
        ),
    ]
