# Generated by Django 4.2.20 on 2025-04-23 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the country', max_length=64, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the currency.', max_length=64, unique=True, verbose_name='Name')),
                ('iso', models.CharField(help_text='The unique 3 characters representing this currently', max_length=3, unique=True, verbose_name='ISO')),
                ('symbol', models.CharField(default='?', help_text='The symbol that this currency uses.', max_length=16, verbose_name='Symbol')),
                ('long_symbol', models.CharField(default=None, help_text='The long symbol that this currency uses that is unique to itself.', max_length=32, null=True, unique=True, verbose_name='Long Symbol')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the region.', max_length=64, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='SubRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name for the sub region.', max_length=64, unique=True, verbose_name='Name')),
                ('code', models.CharField(help_text='The code for the sub region.', max_length=16, unique=True, verbose_name='Code')),
                ('region', models.ForeignKey(help_text='Region that this subregion belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='subregion_of', to='location.region')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the state', max_length=64, verbose_name='Name')),
                ('latitude', models.FloatField(help_text='The latitude of the state.', verbose_name='Latitude')),
                ('longitude', models.FloatField(help_text='The longitude of the state.', verbose_name='Longitude')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='state_of', to='location.country')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.ForeignKey(default=None, help_text='The offical currency of the country', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offical_currency', to='location.currency'),
        ),
        migrations.AddField(
            model_name='country',
            name='sub_region',
            field=models.ForeignKey(help_text='Sub region this country is located in', on_delete=django.db.models.deletion.PROTECT, related_name='country_of', to='location.subregion'),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('latitude', models.FloatField(help_text='The latitude of the state.', verbose_name='Latitude')),
                ('longitude', models.FloatField(help_text='The longitude of the state.', verbose_name='Longitude')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='city_of', to='location.state')),
            ],
        ),
    ]
